apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ROUTE}}
  namespace: i468166
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    matchLabels:
      app: {{ROUTE}}
  template:
    metadata:
      labels:
        app: {{ROUTE}}
    spec:
      containers:
      - name: {{ROUTE}}
        envFrom:
        - configMapRef:
          name: {{ROUTE}}
        image: ghcr.io/nickonos/spotify/{{ROUTE}}
        ports:
        - containerPort: 5175
          name: rest
          protocol: TCP
 
