name: {{ROUTE}}

on: 
  push:
    paths:
      - 'services/{{ROUTE}}/**'
    branches:
      - main
  pull_request:
    paths:
      - 'services/{{ROUTE}}/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/{{ROUTE}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go mod download
      - run: go build -o main .
      - run: go test -v ./...