apiVersion: v1
kind: Service
metadata:
  name: {{ROUTE}}
  namespace: i468166
spec:
  type: ClusterIP
  ports:
  - port: 5175
    targetPort: 5175  
    name: rest
    protocol: TCP
  selector:
    app: {{ROUTE}}

    