version: "3.9"
services:
  gateway:
    build:
      dockerfile: services/gateway/Dockerfile
      context: .
    ports:
      - "5175:5175"
    environment:
      NATS_URL: nats://message_broker:4222
    depends_on:
      - message_broker
    links:
      - message_broker

  identity:
    build:
      context: .
      dockerfile: services/identity/Dockerfile
    environment:
      NATS_URL: nats://message_broker:4222
    depends_on:
      - message_broker
    links:
      - message_broker
  song:
    build:
      dockerfile: services/song/Dockerfile
      context: .
    environment:
      NATS_URL: nats://message_broker:4222
      DB_STRING: postgres://root:root@song_db:5432?sslmode=disable
    depends_on:
      - message_broker
      - song_db
    links:
      - message_broker
      - song_db

  song_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=song
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  message_broker:
    image: nats:latest
    command: "-c /etc/nats.conf -m 8222"
    volumes:
      - ./nats.conf:/etc/nats.conf
    ports:
      - "8222:8222"
volumes:
  postgres_db:
    driver: local