version: "3.9"
services:
  gateway:
    build:
      dockerfile: services/gateway/Dockerfile
      context: .
    ports:
      - "5175:5175"
    environment:
      NATS_URL: ${NATS_URL}
      TOKEN_SECRET: ${TOKEN_SECRET}
    depends_on:
      - message_broker
    links:
      - message_broker

  identity:
    build:
      context: .
      dockerfile: services/identity/Dockerfile
    environment:
      NATS_URL: ${NATS_URL}
    depends_on:
      - message_broker
    links:
      - message_broker
  song:
    build:
      dockerfile: services/song/Dockerfile
      context: .
    environment:
      NATS_URL: nats://message_broker:4222
      DB_STRING: root:root@tcp(song_db:3306)/song
    depends_on:
      song_db:
        condition: service_healthy
      message_broker:
        condition: service_started
    links:
      - message_broker
      - song_db

  authorization:
    build:
      dockerfile: services/authorization/Dockerfile
      context: .
    environment:
      NATS_URL: ${NATS_URL}
      SPOTIFY_URL: ${SPOTIFY_URL}
      SPOTIFY_AUTH_URL: ${SPOTIFY_AUTH_URL}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      DB_STRING: root:root@tcp(authorization_db:3306)/authorization
      TOKEN_SECRET: ${TOKEN_SECRET}
    depends_on:
      authorization_db:
        condition: service_healthy
      message_broker:
        condition: service_started
    links:
      - message_broker
      - authorization_db

  authorization_db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: authorization
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - authorization_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
  
  song_db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: song
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - song_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 10

  message_broker:
    image: nats:latest
    command: "-c /etc/nats.conf -m 8222"
    volumes:
      - ./nats.conf:/etc/nats.conf
    ports:
      - "8222:8222"
volumes:
  song_db:
    driver: local
  authorization_db:
    driver: local