apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  namespace: i468166
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  selector:
    app: authorization
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
      - name: authorization
        image: ghcr.io/nickonos/spotify/authorization
        ports:
        - containerPort: 5175
          name: rest
          protocol: TCP
        envFrom:
        - configMapRef:
            name: authorization
 
