apiVersion: v1
kind: Service
metadata:
  name: authorization
  namespace: student
spec:
  type: ClusterIP
  ports:
    - containerPort: 5175
      name: rest
      protocol: TCP
  selector:
    app: authorization
    
