apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: student
spec:
  type: ClusterIP
  ports:
    - containerPort: 5175
      name: rest
      protocol: TCP
  selector:
    app: gateway
