apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: i468166
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5175  
    name: rest
    protocol: TCP
  selector:
    app: gateway
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway
  namespace: i468166
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

    
