apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: i468166
spec:
  type: ClusterIP
  ports:
  - containerPort:
    port: 5175
    name: rest
    protocol: TCP
  selector:
    app: identity

    
