apiVersion: v1
kind: Service
metadata:
  name: song
  namespace: i468166
spec:
  type: ClusterIP
  ports:
  - port: 5175
    targetPort: 5175  
    name: rest
    protocol: TCP
  selector:
    app: song
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: song
  namespace: i468166
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: song
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1

    
