name: song

on:
  push:
    paths:
      - "services/song/**"
      - ".github/workflows/**"
    branches:
      - main
  pull_request:
    paths:
      - "services/song/**"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/song
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: go mod download
      - run: go build -o main .
      - run: go test -v ./...

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/nickonos/spotify/song:${{ github.sha }} -f services/song/Dockerfile .
          docker push ghcr.io/nickonos/spotify/song:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: publish
    if: github.event_name == 'push'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login Kubernetes
        run: ~/K8s_setup_Nick.sh
      
      - name: Deploy
        uses: azure/k8s-deploy@v4
        with: 
          manifests: |
            .github/manifests/song-deployment.yaml
            .github/manifests/song-service.yaml
          namespace: i468166
          images: |
            ghcr.io/nickonos/spotify/song:${{ github.sha }}
       
